hostname: autovpn-rr2
is_deployed: true
router_bgp:
  as: '65000'
  router_id: 192.168.31.2
  bgp:
    default:
      ipv4_unicast: false
  maximum_paths:
    paths: 16
  updates:
    wait_install: true
  redistribute_routes:
  - source_protocol: connected
    route_map: RM-CONN-2-BGP
  bgp_cluster_id: 192.168.31.2
  listen_ranges:
  - prefix: 192.168.130.0/24
    peer_group: WAN-OVERLAY-PEERS
    remote_as: '65000'
  peer_groups:
  - name: WAN-OVERLAY-PEERS
    type: wan
    update_source: Dps1
    bfd: true
    password: htm4AZe9mIQOO1uiMuGgYQ==
    send_community: all
    maximum_routes: 0
    remote_as: '65000'
    route_reflector_client: true
  - name: RR-OVERLAY-PEERS
    type: wan
    update_source: Dps1
    bfd: true
    send_community: all
    maximum_routes: 0
    remote_as: '65000'
  address_family_evpn:
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: true
    - name: RR-OVERLAY-PEERS
      activate: true
    next_hop:
      resolution_disabled: true
  address_family_ipv4:
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: false
    - name: RR-OVERLAY-PEERS
      activate: false
  address_family_path_selection:
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: true
    - name: RR-OVERLAY-PEERS
      activate: true
    bgp:
      additional_paths:
        receive: true
        send:
          any: true
  neighbors:
  - ip_address: 192.168.131.1
    peer_group: RR-OVERLAY-PEERS
    peer: autovpn-rr1
    description: autovpn-rr1
  vrfs:
  - name: default
    rd: 192.168.31.2:1
    route_targets:
      import:
      - address_family: evpn
        route_targets:
        - '1:1'
      export:
      - address_family: evpn
        route_targets:
        - '1:1'
        - route-map RM-EVPN-EXPORT-VRF-DEFAULT
service_routing_protocols_model: multi-agent
ip_routing: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
spanning_tree:
  mode: none
vrfs:
- name: MGMT
  ip_routing: false
platform:
  sfe:
    data_plane_cpu_allocation_max: 2
management_api_http:
  enable_vrfs:
  - name: MGMT
  enable_https: true
ethernet_interfaces:
- name: Ethernet1
  peer_type: l3_interface
  ip_address: 10.8.8.8/31
  shutdown: false
  type: routed
loopback_interfaces:
- name: Loopback0
  description: Router_ID
  shutdown: false
  ip_address: 192.168.31.2/32
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 192.168.31.0/24 eq 32
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
- name: RM-EVPN-EXPORT-VRF-DEFAULT
  sequence_numbers:
  - sequence: 30
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
static_routes:
- destination_address_prefix: 0.0.0.0/0
  gateway: 10.8.8.9
ip_security:
  ike_policies:
  - name: AUTOVPN-IKE
    local_id: 192.168.131.2
  sa_policies:
  - name: AUTOVPN-SA
  profiles:
  - name: AUTOVPN
    ike_policy: AUTOVPN-IKE
    sa_policy: AUTOVPN-SA
    connection: start
    shared_key: ABCDEF1234567890
    dpd:
      interval: 10
      time: 50
      action: clear
    mode: transport
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
router_path_selection:
  tcp_mss_ceiling:
    ipv4_segment_size: auto
  path_groups:
  - name: MPLS
    id: 100
  - name: INET
    id: 101
    local_interfaces:
    - name: Ethernet1
    static_peers:
    - router_ip: 192.168.131.1
      name: autovpn-rr1
      ipv4_addresses:
      - 10.7.7.7
    ipsec_profile: AUTOVPN
  - name: LTE
    id: 102
    ipsec_profile: AUTOVPN
  peer_dynamic_source: stun
  load_balance_policies:
  - name: LB-CONTROL-PLANE-PROFILE
    path_groups:
    - name: INET
  - name: LB-PROD-AVT-POLICY-VOICE
    path_groups:
    - name: INET
  - name: LB-PROD-AVT-POLICY-VIDEO
    path_groups:
    - name: INET
  - name: LB-PROD-AVT-POLICY-DEFAULT
    path_groups:
    - name: INET
  - name: LB-DEFAULT-AVT-POLICY-IT
    path_groups:
    - name: MPLS
    - name: INET
      priority: 2
  policies:
  - name: PROD-AVT-POLICY
    rules:
    - id: 10
      application_profile: VOICE
      load_balance: LB-PROD-AVT-POLICY-VOICE
    - id: 20
      application_profile: VIDEO
      load_balance: LB-PROD-AVT-POLICY-VIDEO
    default_match:
      load_balance: LB-PROD-AVT-POLICY-DEFAULT
  - name: DEFAULT-AVT-POLICY-WITH-CP
    rules:
    - id: 10
      application_profile: CONTROL-PLANE-APPLICATION-PROFILE
      load_balance: LB-CONTROL-PLANE-PROFILE
    - id: 20
      application_profile: IT
      load_balance: LB-DEFAULT-AVT-POLICY-IT
  vrfs:
  - name: default
    path_selection_policy: DEFAULT-AVT-POLICY-WITH-CP
  - name: PROD
    path_selection_policy: PROD-AVT-POLICY
stun:
  server:
    local_interfaces:
    - Ethernet1
application_traffic_recognition:
  application_profiles:
  - name: VOICE
  - name: VIDEO
  - name: IT
  - name: CONTROL-PLANE-APPLICATION-PROFILE
    applications:
    - name: CONTROL-PLANE-APPLICATION
  applications:
    ipv4_applications:
    - name: CONTROL-PLANE-APPLICATION
      src_prefix_set_name: CONTROL-PLANE-APP-SRC-PREFIXES
  field_sets:
    ipv4_prefixes:
    - name: CONTROL-PLANE-APP-SRC-PREFIXES
      prefix_values:
      - 192.168.131.2/32
dps_interfaces:
- name: Dps1
  description: DPS Interface
  ip_address: 192.168.131.2/32
vxlan_interface:
  Vxlan1:
    description: autovpn-rr2_VTEP
    vxlan:
      udp_port: 4789
      source_interface: Dps1
      vrfs:
      - name: default
        vni: 1
