hostname: cv-pathfinder-edge-no-common-path-group
is_deployed: true
router_bgp:
  as: '65000'
  router_id: 192.168.42.6
  bgp:
    default:
      ipv4_unicast: false
  maximum_paths:
    paths: 16
  updates:
    wait_install: true
  redistribute_routes:
  - source_protocol: connected
    route_map: RM-CONN-2-BGP
  peer_groups:
  - name: WAN-OVERLAY-PEERS
    type: wan
    update_source: Dps1
    bfd: true
    password: htm4AZe9mIQOO1uiMuGgYQ==
    send_community: all
    maximum_routes: 0
    remote_as: '65000'
  address_family_evpn:
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: true
  address_family_ipv4:
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: false
  address_family_ipv4_sr_te:
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: true
  address_family_link_state:
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: true
    path_selection:
      roles:
        producer: true
  address_family_path_selection:
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: true
    bgp:
      additional_paths:
        receive: true
        send:
          any: true
  neighbors:
  - ip_address: 192.168.144.1
    peer_group: WAN-OVERLAY-PEERS
    peer: cv-pathfinder-pathfinder
    description: cv-pathfinder-pathfinder
  vrfs:
  - name: default
    rd: 192.168.42.6:1
    route_targets:
      import:
      - address_family: evpn
        route_targets:
        - '1:1'
      export:
      - address_family: evpn
        route_targets:
        - '1:1'
        - route-map RM-EVPN-EXPORT-VRF-DEFAULT
  - name: IT
    router_id: 192.168.42.6
    rd: 192.168.42.6:100
    route_targets:
      import:
      - address_family: evpn
        route_targets:
        - 100:100
      export:
      - address_family: evpn
        route_targets:
        - 100:100
    redistribute_routes:
    - source_protocol: connected
  - name: PROD
    router_id: 192.168.42.6
    rd: 192.168.42.6:42
    route_targets:
      import:
      - address_family: evpn
        route_targets:
        - '42:42'
      export:
      - address_family: evpn
        route_targets:
        - '42:42'
    redistribute_routes:
    - source_protocol: connected
service_routing_protocols_model: multi-agent
ip_routing: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
spanning_tree:
  mode: none
vrfs:
- name: MGMT
  ip_routing: false
- name: IT
  tenant: TenantA
  ip_routing: true
- name: PROD
  tenant: TenantA
  ip_routing: true
management_api_http:
  enable_vrfs:
  - name: MGMT
  enable_https: true
ethernet_interfaces:
- name: Ethernet1
  peer_type: l3_interface
  ip_address: dhcp
  shutdown: false
  type: routed
  dhcp_client_accept_default_route: true
  flow_tracker:
    hardware: WAN-FLOW-TRACKER
loopback_interfaces:
- name: Loopback0
  description: Router_ID
  shutdown: false
  ip_address: 192.168.42.6/32
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 192.168.42.0/24 eq 32
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
- name: RM-EVPN-EXPORT-VRF-DEFAULT
  sequence_numbers:
  - sequence: 30
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
flow_tracking:
  hardware:
    trackers:
    - name: WAN-FLOW-TRACKER
      record_export:
        on_inactive_timeout: 70000
        on_interval: 5000
      exporters:
      - name: DPI-EXPORTER
        collector:
          host: 127.0.0.1
        local_interface: Loopback0
        template_interval: 5000
    shutdown: false
ip_security:
  ike_policies:
  - name: DP-IKE-POLICY
    local_id: 192.168.142.6
  - name: CP-IKE-POLICY
    local_id: 192.168.142.6
  sa_policies:
  - name: DP-SA-POLICY
    esp:
      encryption: aes128
    pfs_dh_group: 14
  - name: CP-SA-POLICY
    esp:
      encryption: aes128
    pfs_dh_group: 14
  profiles:
  - name: DP-PROFILE
    ike_policy: DP-IKE-POLICY
    sa_policy: DP-SA-POLICY
    connection: start
    shared_key: ABCDEF1234567890666
    dpd:
      interval: 10
      time: 50
      action: clear
    mode: transport
  - name: CP-PROFILE
    ike_policy: CP-IKE-POLICY
    sa_policy: CP-SA-POLICY
    connection: start
    shared_key: ABCDEF1234567890
    dpd:
      interval: 10
      time: 50
      action: clear
    mode: transport
  key_controller:
    profile: DP-PROFILE
router_adaptive_virtual_topology:
  topology_role: edge
  region:
    name: AVD_Land_East
    id: 43
  zone:
    name: DEFAULT-ZONE
    id: 1
  site:
    name: Site512
    id: 512
  profiles:
  - name: CONTROL-PLANE-PROFILE
    load_balance_policy: LB-CONTROL-PLANE-PROFILE
  - name: PROD-AVT-POLICY-VOICE
    load_balance_policy: LB-PROD-AVT-POLICY-VOICE
  - name: PROD-AVT-POLICY-VIDEO
    load_balance_policy: LB-PROD-AVT-POLICY-VIDEO
  - name: PROD-AVT-POLICY-DEFAULT
    load_balance_policy: LB-PROD-AVT-POLICY-DEFAULT
  - name: DEFAULT-AVT-POLICY-VIDEO
    load_balance_policy: LB-DEFAULT-AVT-POLICY-VIDEO
  - name: DEFAULT-AVT-POLICY-DEFAULT
    load_balance_policy: LB-DEFAULT-AVT-POLICY-DEFAULT
  vrfs:
  - name: default
    policy: DEFAULT-AVT-POLICY-WITH-CP
    profiles:
    - name: CONTROL-PLANE-PROFILE
      id: 254
    - name: DEFAULT-AVT-POLICY-VIDEO
      id: 3
    - name: DEFAULT-AVT-POLICY-DEFAULT
      id: 1
  - name: PROD
    policy: PROD-AVT-POLICY
    profiles:
    - name: PROD-AVT-POLICY-VOICE
      id: 2
    - name: PROD-AVT-POLICY-VIDEO
      id: 4
    - name: PROD-AVT-POLICY-DEFAULT
      id: 1
  - name: IT
    policy: DEFAULT-AVT-POLICY
    profiles:
    - name: DEFAULT-AVT-POLICY-VIDEO
      id: 3
    - name: DEFAULT-AVT-POLICY-DEFAULT
      id: 1
  policies:
  - name: PROD-AVT-POLICY
    matches:
    - application_profile: VOICE
      avt_profile: PROD-AVT-POLICY-VOICE
    - application_profile: VIDEO
      avt_profile: PROD-AVT-POLICY-VIDEO
    - application_profile: default
      avt_profile: PROD-AVT-POLICY-DEFAULT
  - name: DEFAULT-AVT-POLICY
    matches:
    - application_profile: VIDEO
      avt_profile: DEFAULT-AVT-POLICY-VIDEO
    - application_profile: default
      avt_profile: DEFAULT-AVT-POLICY-DEFAULT
  - name: DEFAULT-AVT-POLICY-WITH-CP
    matches:
    - application_profile: CONTROL-PLANE-APPLICATION-PROFILE
      avt_profile: CONTROL-PLANE-PROFILE
    - application_profile: VIDEO
      avt_profile: DEFAULT-AVT-POLICY-VIDEO
    - application_profile: default
      avt_profile: DEFAULT-AVT-POLICY-DEFAULT
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
router_path_selection:
  tcp_mss_ceiling:
    ipv4_segment_size: auto
  path_groups:
  - name: Satellite
    id: 104
    local_interfaces:
    - name: Ethernet1
    dynamic_peers:
      enabled: true
    ipsec_profile: CP-PROFILE
  load_balance_policies:
  - name: LB-CONTROL-PLANE-PROFILE
    path_groups:
    - name: Satellite
  - name: LB-PROD-AVT-POLICY-VOICE
    jitter: 42
  - name: LB-PROD-AVT-POLICY-VIDEO
    loss_rate: '42.0'
  - name: LB-PROD-AVT-POLICY-DEFAULT
  - name: LB-DEFAULT-AVT-POLICY-VIDEO
  - name: LB-DEFAULT-AVT-POLICY-DEFAULT
router_traffic_engineering:
  enabled: true
application_traffic_recognition:
  application_profiles:
  - name: VOICE
    applications:
    - name: CUSTOM-VOICE-APPLICATION
  - name: VIDEO
    categories:
    - name: VIDEO1
    applications:
    - name: CUSTOM-APPLICATION-1
    - name: skype
  - name: CONTROL-PLANE-APPLICATION-PROFILE
    applications:
    - name: CONTROL-PLANE-APPLICATION
  categories:
  - name: VIDEO1
    applications:
    - name: CUSTOM-APPLICATION-2
    - name: microsoft-teams
  applications:
    ipv4_applications:
    - name: CUSTOM-APPLICATION-1
      protocols:
      - tcp
      src_prefix_set_name: CUSTOM-SRC-PREFIX-1
      dest_prefix_set_name: CUSTOM-DEST-PREFIX-1
    - name: CUSTOM-APPLICATION-2
      protocols:
      - tcp
      tcp_src_port_set_name: TCP-SRC-2
      tcp_dest_port_set_name: TCP-DEST-2
    - name: CONTROL-PLANE-APPLICATION
      dest_prefix_set_name: CONTROL-PLANE-APP-DEST-PREFIXES
  field_sets:
    l4_ports:
    - name: TCP-SRC-2
      port_values:
      - '42'
    - name: TCP-DEST-2
      port_values:
      - '666'
      - '777'
    ipv4_prefixes:
    - name: CUSTOM-SRC-PREFIX-1
      prefix_values:
      - 42.42.42.0/24
    - name: CUSTOM-DEST-PREFIX-1
      prefix_values:
      - 6.6.6.0/24
    - name: CONTROL-PLANE-APP-DEST-PREFIXES
      prefix_values:
      - 192.168.144.1/32
dps_interfaces:
- name: Dps1
  description: DPS Interface
  ip_address: 192.168.142.6/32
  flow_tracker:
    hardware: WAN-FLOW-TRACKER
vxlan_interface:
  Vxlan1:
    description: cv-pathfinder-edge-no-common-path-group_VTEP
    vxlan:
      udp_port: 4789
      source_interface: Dps1
      vrfs:
      - name: default
        vni: 1
      - name: IT
        vni: 100
      - name: PROD
        vni: 42
metadata:
  cv_tags:
    device_tags:
    - name: Role
      value: edge
    - name: Region
      value: AVD_Land_East
    - name: Zone
      value: DEFAULT-ZONE
    - name: Site
      value: Site512
    interface_tags:
    - interface: Ethernet1
      tags:
      - name: Type
        value: wan
      - name: Carrier
        value: Inmrasat
      - name: Circuit
        value: S512
  cv_pathfinder:
    role: edge
    vtep_ip: 192.168.142.6
    region: AVD_Land_East
    zone: DEFAULT-ZONE
    site: Site512
    interfaces:
    - name: Ethernet1
      carrier: Inmrasat
      pathgroup: Satellite
    pathfinders:
    - vtep_ip: 192.168.144.1
