hostname: cv-pathfinder-pathfinder
is_deployed: true
router_bgp:
  as: '65000'
  router_id: 192.168.44.1
  bgp:
    default:
      ipv4_unicast: false
  maximum_paths:
    paths: 16
  updates:
    wait_install: true
  redistribute_routes:
  - source_protocol: connected
    route_map: RM-CONN-2-BGP
  bgp_cluster_id: 192.168.44.1
  listen_ranges:
  - prefix: 192.168.142.0/24
    peer_group: WAN-OVERLAY-PEERS
    remote_as: '65000'
  - prefix: 192.168.143.0/24
    peer_group: WAN-OVERLAY-PEERS
    remote_as: '65000'
  peer_groups:
  - name: WAN-OVERLAY-PEERS
    type: wan
    update_source: Dps1
    bfd: true
    password: htm4AZe9mIQOO1uiMuGgYQ==
    send_community: all
    maximum_routes: 0
    remote_as: '65000'
    route_reflector_client: true
  address_family_evpn:
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: true
    next_hop:
      resolution_disabled: true
  address_family_ipv4:
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: false
  address_family_ipv4_sr_te:
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: true
  address_family_link_state:
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: true
      missing_policy:
        direction_out_action: deny
    path_selection:
      roles:
        consumer: true
        propagator: true
  address_family_path_selection:
    peer_groups:
    - name: WAN-OVERLAY-PEERS
      activate: true
    bgp:
      additional_paths:
        receive: true
        send:
          any: true
  vrfs:
  - name: default
    rd: 192.168.44.1:1
    route_targets:
      import:
      - address_family: evpn
        route_targets:
        - '1:1'
      export:
      - address_family: evpn
        route_targets:
        - '1:1'
        - route-map RM-EVPN-EXPORT-VRF-DEFAULT
service_routing_protocols_model: multi-agent
ip_routing: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
spanning_tree:
  mode: none
vrfs:
- name: MGMT
  ip_routing: false
platform:
  sfe:
    data_plane_cpu_allocation_max: 1
management_api_http:
  enable_vrfs:
  - name: MGMT
  enable_https: true
ethernet_interfaces:
- name: Ethernet1
  peer_type: l3_interface
  ip_address: 10.7.7.7/31
  shutdown: false
  type: routed
  flow_tracker:
    hardware: WAN-FLOW-TRACKER
- name: Ethernet2
  peer_type: l3_interface
  ip_address: 172.16.0.1/31
  shutdown: false
  type: routed
  flow_tracker:
    hardware: WAN-FLOW-TRACKER
- name: Ethernet3
  peer_type: l3_interface
  ip_address: 10.9.9.9/31
  shutdown: false
  type: routed
  flow_tracker:
    hardware: WAN-FLOW-TRACKER
loopback_interfaces:
- name: Loopback0
  description: Router_ID
  shutdown: false
  ip_address: 192.168.44.1/32
prefix_lists:
- name: PL-LOOPBACKS-EVPN-OVERLAY
  sequence_numbers:
  - sequence: 10
    action: permit 192.168.44.0/24 eq 32
route_maps:
- name: RM-CONN-2-BGP
  sequence_numbers:
  - sequence: 10
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
- name: RM-EVPN-EXPORT-VRF-DEFAULT
  sequence_numbers:
  - sequence: 30
    type: permit
    match:
    - ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
static_routes:
- destination_address_prefix: 0.0.0.0/0
  gateway: 10.7.7.6
flow_tracking:
  hardware:
    trackers:
    - name: WAN-FLOW-TRACKER
      record_export:
        on_inactive_timeout: 70000
        on_interval: 5000
      exporters:
      - name: DPI-EXPORTER
        collector:
          host: 127.0.0.1
        local_interface: Loopback0
        template_interval: 5000
    shutdown: false
ip_security:
  ike_policies:
  - name: CP-IKE-POLICY
    local_id: 192.168.144.1
  sa_policies:
  - name: CP-SA-POLICY
    esp:
      encryption: aes128
    pfs_dh_group: 14
  profiles:
  - name: CP-PROFILE
    ike_policy: CP-IKE-POLICY
    sa_policy: CP-SA-POLICY
    connection: start
    shared_key: ABCDEF1234567890
    dpd:
      interval: 10
      time: 50
      action: clear
    mode: transport
router_adaptive_virtual_topology:
  topology_role: pathfinder
  profiles:
  - name: CONTROL-PLANE-PROFILE
    load_balance_policy: LB-CONTROL-PLANE-PROFILE
  - name: PROD-AVT-POLICY-VOICE
    load_balance_policy: LB-PROD-AVT-POLICY-VOICE
  - name: PROD-AVT-POLICY-VIDEO
    load_balance_policy: LB-PROD-AVT-POLICY-VIDEO
  - name: PROD-AVT-POLICY-DEFAULT
    load_balance_policy: LB-PROD-AVT-POLICY-DEFAULT
  - name: DEFAULT-AVT-POLICY-VIDEO
    load_balance_policy: LB-DEFAULT-AVT-POLICY-VIDEO
  - name: DEFAULT-AVT-POLICY-DEFAULT
    load_balance_policy: LB-DEFAULT-AVT-POLICY-DEFAULT
  - name: TRANSIT-AVT-POLICY-VOICE
    load_balance_policy: LB-TRANSIT-AVT-POLICY-VOICE
  - name: TRANSIT-AVT-POLICY-DEFAULT
    load_balance_policy: LB-TRANSIT-AVT-POLICY-DEFAULT
  vrfs:
  - name: default
    policy: DEFAULT-AVT-POLICY-WITH-CP
    profiles:
    - name: CONTROL-PLANE-PROFILE
      id: 254
    - name: DEFAULT-AVT-POLICY-VIDEO
      id: 3
    - name: DEFAULT-AVT-POLICY-DEFAULT
      id: 1
  - name: PROD
    policy: PROD-AVT-POLICY
    profiles:
    - name: PROD-AVT-POLICY-VOICE
      id: 2
    - name: PROD-AVT-POLICY-VIDEO
      id: 4
    - name: PROD-AVT-POLICY-DEFAULT
      id: 1
  - name: IT
    policy: DEFAULT-AVT-POLICY
    profiles:
    - name: DEFAULT-AVT-POLICY-VIDEO
      id: 3
    - name: DEFAULT-AVT-POLICY-DEFAULT
      id: 1
  - name: TRANSIT
    policy: TRANSIT-AVT-POLICY
    profiles:
    - name: TRANSIT-AVT-POLICY-VOICE
      id: 42
    - name: TRANSIT-AVT-POLICY-DEFAULT
      id: 1
  policies:
  - name: PROD-AVT-POLICY
    matches:
    - application_profile: VOICE
      avt_profile: PROD-AVT-POLICY-VOICE
    - application_profile: VIDEO
      avt_profile: PROD-AVT-POLICY-VIDEO
    - application_profile: default
      avt_profile: PROD-AVT-POLICY-DEFAULT
  - name: DEFAULT-AVT-POLICY
    matches:
    - application_profile: VIDEO
      avt_profile: DEFAULT-AVT-POLICY-VIDEO
    - application_profile: default
      avt_profile: DEFAULT-AVT-POLICY-DEFAULT
  - name: TRANSIT-AVT-POLICY
    matches:
    - application_profile: VOICE
      avt_profile: TRANSIT-AVT-POLICY-VOICE
    - application_profile: default
      avt_profile: TRANSIT-AVT-POLICY-DEFAULT
  - name: DEFAULT-AVT-POLICY-WITH-CP
    matches:
    - application_profile: CONTROL-PLANE-APPLICATION-PROFILE
      avt_profile: CONTROL-PLANE-PROFILE
    - application_profile: VIDEO
      avt_profile: DEFAULT-AVT-POLICY-VIDEO
    - application_profile: default
      avt_profile: DEFAULT-AVT-POLICY-DEFAULT
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
router_path_selection:
  tcp_mss_ceiling:
    ipv4_segment_size: auto
  path_groups:
  - name: MPLS
    id: 100
    local_interfaces:
    - name: Ethernet2
  - name: INET
    id: 101
    local_interfaces:
    - name: Ethernet1
    - name: Ethernet3
    ipsec_profile: CP-PROFILE
  - name: LTE
    id: 102
    ipsec_profile: CP-PROFILE
  - name: Equinix
    id: 103
    ipsec_profile: CP-PROFILE
  - name: Satellite
    id: 104
    ipsec_profile: CP-PROFILE
  peer_dynamic_source: stun
  load_balance_policies:
  - name: LB-CONTROL-PLANE-PROFILE
    path_groups:
    - name: INET
    - name: MPLS
  - name: LB-PROD-AVT-POLICY-VOICE
    path_groups:
    - name: MPLS
    - name: INET
      priority: 2
    jitter: 42
  - name: LB-PROD-AVT-POLICY-VIDEO
    path_groups:
    - name: MPLS
    - name: LTE
    - name: INET
      priority: 2
    loss_rate: '42.0'
  - name: LB-PROD-AVT-POLICY-DEFAULT
    path_groups:
    - name: INET
    - name: MPLS
      priority: 2
  - name: LB-DEFAULT-AVT-POLICY-VIDEO
    path_groups:
    - name: MPLS
    - name: INET
  - name: LB-DEFAULT-AVT-POLICY-DEFAULT
    path_groups:
    - name: INET
    - name: Equinix
    - name: MPLS
      priority: 42
  - name: LB-TRANSIT-AVT-POLICY-VOICE
    path_groups:
    - name: MPLS
    - name: INET
      priority: 2
  - name: LB-TRANSIT-AVT-POLICY-DEFAULT
    path_groups:
    - name: INET
    - name: MPLS
      priority: 2
router_traffic_engineering:
  enabled: true
stun:
  server:
    local_interfaces:
    - Ethernet1
    - Ethernet2
    - Ethernet3
application_traffic_recognition:
  application_profiles:
  - name: VOICE
    applications:
    - name: CUSTOM-VOICE-APPLICATION
  - name: VIDEO
    categories:
    - name: VIDEO1
    applications:
    - name: CUSTOM-APPLICATION-1
    - name: skype
  - name: CONTROL-PLANE-APPLICATION-PROFILE
    applications:
    - name: CONTROL-PLANE-APPLICATION
  categories:
  - name: VIDEO1
    applications:
    - name: CUSTOM-APPLICATION-2
    - name: microsoft-teams
  applications:
    ipv4_applications:
    - name: CUSTOM-APPLICATION-1
      protocols:
      - tcp
      src_prefix_set_name: CUSTOM-SRC-PREFIX-1
      dest_prefix_set_name: CUSTOM-DEST-PREFIX-1
    - name: CUSTOM-APPLICATION-2
      protocols:
      - tcp
      tcp_src_port_set_name: TCP-SRC-2
      tcp_dest_port_set_name: TCP-DEST-2
    - name: CONTROL-PLANE-APPLICATION
      src_prefix_set_name: CONTROL-PLANE-APP-SRC-PREFIXES
  field_sets:
    l4_ports:
    - name: TCP-SRC-2
      port_values:
      - '42'
    - name: TCP-DEST-2
      port_values:
      - '666'
      - '777'
    ipv4_prefixes:
    - name: CUSTOM-SRC-PREFIX-1
      prefix_values:
      - 42.42.42.0/24
    - name: CUSTOM-DEST-PREFIX-1
      prefix_values:
      - 6.6.6.0/24
    - name: CONTROL-PLANE-APP-SRC-PREFIXES
      prefix_values:
      - 192.168.144.1/32
dps_interfaces:
- name: Dps1
  description: DPS Interface
  ip_address: 192.168.144.1/32
  flow_tracker:
    hardware: WAN-FLOW-TRACKER
vxlan_interface:
  Vxlan1:
    description: cv-pathfinder-pathfinder_VTEP
    vxlan:
      udp_port: 4789
      source_interface: Dps1
      vrfs:
      - name: default
        vni: 1
metadata:
  cv_tags:
    device_tags:
    - name: Role
      value: pathfinder
    - name: PathfinderSet
      value: PATHFINDERS
    interface_tags:
    - interface: Ethernet1
      tags:
      - name: Type
        value: wan
      - name: Carrier
        value: Bouygues_Telecom
      - name: Circuit
        value: '777'
    - interface: Ethernet2
      tags:
      - name: Type
        value: wan
      - name: Carrier
        value: Colt
      - name: Circuit
        value: '10000'
    - interface: Ethernet3
      tags:
      - name: Type
        value: wan
      - name: Carrier
        value: Another-ISP
      - name: Circuit
        value: '999'
  cv_pathfinder:
    role: pathfinder
    vtep_ip: 192.168.144.1
    interfaces:
    - name: Ethernet1
      carrier: Bouygues_Telecom
      pathgroup: INET
      public_ip: 10.7.7.7
    - name: Ethernet2
      carrier: Colt
      pathgroup: MPLS
      public_ip: 172.16.0.1
    - name: Ethernet3
      carrier: Another-ISP
      pathgroup: INET
      public_ip: 10.9.9.9
    pathgroups:
    - name: MPLS
      carriers:
      - name: Colt
      - name: ATT-MPLS
    - name: INET
      carriers:
      - name: Comcast
      - name: ATT
      - name: Bouygues_Telecom
      - name: SFR
      - name: Orange
      - name: Another-ISP
    - name: LTE
      carriers:
      - name: Comcast-5G
    - name: Equinix
    - name: Satellite
      carriers:
      - name: Inmrasat
    regions:
    - name: AVD_Land_West
      id: 42
      zones:
      - name: DEFAULT-ZONE
        id: 1
        sites:
        - name: Site422
          id: 422
          location:
            address: Somewhere
    - name: AVD_Land_East
      id: 43
      zones:
      - name: DEFAULT-ZONE
        id: 1
        sites:
        - name: Site511
          id: 511
        - name: Site512
          id: 512
    vrfs:
    - name: default
      vni: 1
      avts:
      - id: 254
        name: CONTROL-PLANE-PROFILE
        pathgroups:
        - name: INET
          preference: preferred
        - name: MPLS
          preference: preferred
      - id: 3
        name: DEFAULT-AVT-POLICY-VIDEO
        pathgroups:
        - name: MPLS
          preference: preferred
        - name: INET
          preference: preferred
      - id: 1
        name: DEFAULT-AVT-POLICY-DEFAULT
        pathgroups:
        - name: INET
          preference: preferred
        - name: Equinix
          preference: preferred
        - name: MPLS
          preference: alternate
    - name: PROD
      vni: 42
      avts:
      - constraints:
          jitter: 42
        id: 2
        name: PROD-AVT-POLICY-VOICE
        pathgroups:
        - name: MPLS
          preference: preferred
        - name: INET
          preference: alternate
      - id: 4
        name: PROD-AVT-POLICY-VIDEO
        pathgroups:
        - name: MPLS
          preference: preferred
        - name: LTE
          preference: preferred
        - name: INET
          preference: alternate
      - id: 1
        name: PROD-AVT-POLICY-DEFAULT
        pathgroups:
        - name: INET
          preference: preferred
        - name: MPLS
          preference: alternate
    - name: IT
      vni: 100
      avts:
      - id: 3
        name: DEFAULT-AVT-POLICY-VIDEO
        pathgroups:
        - name: MPLS
          preference: preferred
        - name: INET
          preference: preferred
      - id: 1
        name: DEFAULT-AVT-POLICY-DEFAULT
        pathgroups:
        - name: INET
          preference: preferred
        - name: Equinix
          preference: preferred
        - name: MPLS
          preference: alternate
    - name: TRANSIT
      vni: 66
      avts:
      - id: 42
        name: TRANSIT-AVT-POLICY-VOICE
        pathgroups:
        - name: MPLS
          preference: preferred
        - name: INET
          preference: alternate
      - id: 1
        name: TRANSIT-AVT-POLICY-DEFAULT
        pathgroups:
        - name: INET
          preference: preferred
        - name: MPLS
          preference: alternate
