---
wan_mode: autovpn
type: wan_edge
fabric_name: fabric_wan_role_overlay_routing_protocol

# Not ibgp
overlay_routing_protocol: none

wan_edge:
  defaults:
    loopback_ipv4_pool: 192.168.0.0/24
    vtep_loopback_ipv4_pool: 192.168.1.0/24
  nodes:
    - name: invalid-wan-role-overlay-routing-protocol
      id: 1

expected_error_message: >-
  Only 'ibgp' is supported as 'overlay_routing_protocol' for WAN nodes.
