---
wan_mode: cv-pathfinder
type: wan_edge

bgp_as: 65000

wan_carriers:
  - name: MPLS
    path_group: MPLS

wan_path_groups:
  - name: MPLS
    id: 42

wan_edge:
  defaults:
    loopback_ipv4_pool: 192.168.0.0/24
    vtep_loopback_ipv4_pool: 192.168.1.0/24
  nodes:
    - name: invalid-wan-role-cv-pathfinder-role-1
      # Trying to set edge as RR
      wan_role: server
      evpn_role: server
      id: 1

# If this is not set, the other error message is not triggered
data_plane_cpu_allocation_max: 1

expected_error_message: >-
  'wan_role' must be 'client' when 'cv_pathfinder_role' is set to 'transit' or 'edge'
