---
# Testing autovpn
wan_mode: autovpn

bgp_as: 65000

bgp_peer_groups:
  wan_overlay_peers:
    password: "htm4AZe9mIQOO1uiMuGgYQ=="
    listen_range_prefixes:
      - 192.168.130.0/24

wan_route_servers:
  # Testing having the interface configured with DHCP
  - hostname: autovpn-rr1
    path_groups:
      - name: INET
        interfaces:
          - name: Ethernet1
            ip_address: 10.7.7.7/31
  - hostname: autovpn-rr2

wan_ipsec_profiles:
  control_plane:
    ike_policy_name: AUTOVPN-IKE
    sa_policy_name: AUTOVPN-SA
    profile_name: AUTOVPN
    shared_key: ABCDEF1234567890

default_node_types:
  - node_type: wan_rr
    match_hostnames:
      - "autovpn-rr.*"
  - node_type: wan_edge
    match_hostnames:
      - "autovpn-edge"

wan_edge:
  defaults:
    loopback_ipv4_pool: 192.168.30.0/24
    vtep_loopback_ipv4_pool: 192.168.130.0/24
    filter:
      # TODO find a way to not need this
      always_include_vrfs_in_tenants: [TenantA]
  nodes:
    - name: autovpn-edge
      id: 1
      l3_interfaces:
        - name: Ethernet1
          wan_carrier: Comcast
          wan_circuit_id: 666
          ip: dhcp
          set_default_route: true

wan_rr:
  defaults:
    loopback_ipv4_pool: 192.168.31.0/24
    vtep_loopback_ipv4_pool: 192.168.131.0/24
  nodes:
    - name: autovpn-rr1
      id: 1
      l3_interfaces:
        - name: Ethernet1
          wan_carrier: ATT
          wan_circuit_id: 777
          ip: dhcp
          set_default_route: true
    - name: autovpn-rr2
      id: 2
      l3_interfaces:
        - name: Ethernet1
          wan_carrier: ATT
          wan_circuit_id: 888
          ip: 10.8.8.8/31
          set_default_route: true
          peer_ip: 10.8.8.9

wan_path_groups:
  - name: MPLS
    ipsec: False
    id: 100
  - name: INET
    id: 101
  - name: LTE
    id: 102

wan_carriers:
  - name: Comcast
    path_group: INET
  - name: ATT
    path_group: INET

tenants:
  - name: TenantA
    vrfs:
      - name: default
        vrf_id: 1
      - name: PROD
        vrf_id: 42
      - name: IT
        vrf_id: 100

wan_virtual_topologies:
  vrfs:
    - name: default
      policy: DEFAULT-AVT-POLICY
    - name: PROD
      policy: PROD-AVT-POLICY
  policies:
    - name: PROD-AVT-POLICY
      default_virtual_topology:
        path_groups:
          - names: [INET]
            preference: preferred
      application_virtual_topologies:
        - application_profile: VOICE
          path_groups:
            - names: [INET]
              preference: preferred
        - application_profile: VIDEO
          path_groups:
            - names: [INET]
              preference: preferred
    - name: DEFAULT-AVT-POLICY
      default_virtual_topology:
        drop_unmatched: true
      application_virtual_topologies:
        - application_profile: IT
          path_groups:
            - names: [MPLS]
              preference: preferred
            - names: [INET]
              preference: alternate

application_traffic_recognition:
  application_profiles:
    - name: VIDEO
    - name: IT
    - name: VOICE
