---
# Testing cv-pathfinder
wan_mode: cv-pathfinder

bgp_as: 65000

cv_pathfinder_regions:
  - name: AVD_Land_West
    id: 42
    description: AVD Region
    sites:
      - name: Site422
        id: 422
        location: Somewhere
  - name: AVD_Land_East
    id: 43
    description: AVD Region
    sites:
      - name: Site511
        id: 511
      - name: Site512
        id: 512

bgp_peer_groups:
  wan_overlay_peers:
    password: "htm4AZe9mIQOO1uiMuGgYQ=="
    listen_range_prefixes:
      - 192.168.142.0/24
      - 192.168.143.0/24

wan_route_servers:
  # Not testing the overloading
  - hostname: cv-pathfinder-pathfinder

wan_ipsec_profiles:
  control_plane:
    shared_key: ABCDEF1234567890
  data_plane:
    shared_key: ABCDEF1234567890666

default_node_types:
  - node_type: wan_rr
    match_hostnames:
      - "cv-pathfinder-pathfinder.*"
  - node_type: wan_transit
    match_hostnames:
      - "cv-pathfinder-transit"
  - node_type: wan_edge
    match_hostnames:
      - "cv-pathfinder-edge.*"

wan_edge:
  defaults:
    loopback_ipv4_pool: 192.168.42.0/24
    vtep_loopback_ipv4_pool: 192.168.142.0/24
    filter:
      always_include_vrfs_in_tenants: [TenantA]
  nodes:
    - name: cv-pathfinder-edge
      cv_pathfinder_region: AVD_Land_East
      cv_pathfinder_site: Site511
      id: 1
      l3_interfaces:
        - name: Ethernet1
          wan_carrier: ATT
          wan_circuit_id: 666
          set_default_route: true
          ip: dhcp
        - name: Ethernet2
          wan_carrier: Colt
          wan_circuit_id: 10555
          ip: 172.15.5.5/31
        - name: Ethernet3
          wan_carrier: Comcast-5G
          wan_circuit_id: AF830
          ip: 172.20.20.20/31
          connected_to_pathfinder: False
    - name: cv-pathfinder-edge-no-common-path-group
      cv_pathfinder_region: AVD_Land_East
      cv_pathfinder_site: Site512
      id: 6
      l3_interfaces:
        - name: Ethernet1
          wan_carrier: Inmrasat
          wan_circuit_id: S512
          set_default_route: true
          ip: dhcp

wan_transit:
  defaults:
    loopback_ipv4_pool: 192.168.43.0/24
    vtep_loopback_ipv4_pool: 192.168.143.0/24
    filter:
      always_include_vrfs_in_tenants: [TenantA, TenantB]
  nodes:
    - name: cv-pathfinder-transit
      cv_pathfinder_region: AVD_Land_West
      cv_pathfinder_site: Site422
      id: 1
      l3_interfaces:
        - name: Ethernet1
          wan_carrier: Comcast
          wan_circuit_id: 667
          set_default_route: true
          ip: dhcp
        - name: Ethernet2
          wan_carrier: Colt
          wan_circuit_id: 10666
          ip: 172.16.6.6/31

wan_rr:
  defaults:
    loopback_ipv4_pool: 192.168.44.0/24
    vtep_loopback_ipv4_pool: 192.168.144.0/24
  nodes:
    - name: cv-pathfinder-pathfinder
      id: 1
      l3_interfaces:
        - name: Ethernet1
          wan_carrier: Bouygues_Telecom
          wan_circuit_id: 777
          set_default_route: true
          ip: 10.7.7.7/31
          peer_ip: 10.7.7.6
        - name: Ethernet2
          wan_carrier: Colt
          wan_circuit_id: 10000
          ip: 172.16.0.1/31
        - name: Ethernet3
          wan_carrier: Another-ISP
          wan_circuit_id: 999
          ip: 10.9.9.9/31
    - name: cv-pathfinder-pathfinder1
      id: 2
      l3_interfaces:
        - name: Ethernet1
          wan_carrier: Orange
          wan_circuit_id: 888
          ip: 10.8.8.8/31
    - name: cv-pathfinder-pathfinder2
      id: 3
      l3_interfaces:
        - name: Ethernet1
          wan_carrier: SFR
          wan_circuit_id: 999
          ip: 10.9.9.9/31
        - name: Ethernet2
          wan_carrier: ATT-MPLS
          wan_circuit_id: 10999
          ip: 172.19.9.9/31

wan_path_groups:
  - name: MPLS
    ipsec: false
    # TODO remove one once auto-id is implemented - for now required in schema
    id: 100
  - name: INET
    id: 101
  - name: LTE
    id: 102
  - name: Equinix
    id: 103
  - name: Satellite
    id: 104

wan_carriers:
  - name: Comcast
    path_group: INET
  - name: ATT
    path_group: INET
  - name: Bouygues_Telecom
    path_group: INET
  - name: SFR
    path_group: INET
  - name: Orange
    path_group: INET
  - name: Another-ISP
    path_group: INET
  - name: Colt
    path_group: MPLS
  - name: ATT-MPLS
    path_group: MPLS
  - name: Comcast-5G
    path_group: LTE
  - name: Inmrasat
    path_group: Satellite

tenants:
  - name: TenantA
    vrfs:
      - name: default
        vrf_id: 1
      - name: PROD
        vrf_id: 42
      - name: IT
        vrf_id: 100
  - name: TenantB
    vrfs:
      - name: default
        vrf_id: 1
      - name: TRANSIT
        vrf_id: 66

wan_virtual_topologies:
  vrfs:
    - name: default
      policy: DEFAULT-AVT-POLICY
    - name: PROD
      policy: PROD-AVT-POLICY
    # Testing reusing the same policy as default VRF
    - name: IT
      policy: DEFAULT-AVT-POLICY
    # Testing a VRF only on transit and not edge
    - name: TRANSIT
      policy: TRANSIT-AVT-POLICY
  policies:
    - name: PROD-AVT-POLICY
      default_virtual_topology:
        path_groups:
          - names: [INET]
            preference: preferred
          - names: [MPLS]
            preference: alternate
      application_virtual_topologies:
        - application_profile: VOICE
          path_groups:
            - names: [MPLS]
              preference: preferred
            - names: [INET]
              preference: alternate
          constraints:
            jitter: 42
          id: 2
        - application_profile: VIDEO
          path_groups:
            - names: [MPLS, LTE]
              preference: preferred
            - names: [INET]
              preference: alternate
          constraints:
            loss_rate: 42.0
          id: 4
    - name: DEFAULT-AVT-POLICY
      default_virtual_topology:
        path_groups:
          # No prefence to check the default.
          - names: [INET, Equinix]
          - names: [MPLS]
            preference: 42
      application_virtual_topologies:
        - application_profile: VIDEO
          path_groups:
            - names: [MPLS, INET]
              preference: preferred
          id: 3
    - name: TRANSIT-AVT-POLICY
      default_virtual_topology:
        path_groups:
          - names: [INET]
            preference: preferred
          - names: [MPLS]
            preference: alternate
      application_virtual_topologies:
        - application_profile: VOICE
          path_groups:
            - names: [MPLS]
              preference: preferred
            - names: [INET]
              preference: alternate
          id: 42

application_traffic_recognition:
  application_profiles:
    - name: VIDEO
      # Testing categories filtering
      categories:
        - name: VIDEO1
      applications:
        # Testing applications in application-profiles filtering
        - name: CUSTOM-APPLICATION-1
        # Builtin application that should not raise
        - name: skype
    - name: IT
    - name: VOICE
      applications:
        # Testing applications in application-profiles filtering
        - name: CUSTOM-VOICE-APPLICATION
    # This should not be rendered in any device
    - name: NOT-IN-ANY-POLICY
  categories:
    # This should not be rendered in any device
    - name: NOT-IN-ANY-PROFILE
    - name: VIDEO1
      applications:
        # Testing applications in categories filtering
        - name: CUSTOM-APPLICATION-2
        # Builtin application that should not raise
        - name: microsoft-teams
  applications:
    ipv4_applications:
      # This should not be rendered in any device
      - name: NOT-IN-ANY-PROFILE-NOR-CATEGORY
      - name: CUSTOM-APPLICATION-1
        protocols: [tcp]
        # Testing filtering of prefixes
        src_prefix_set_name: CUSTOM-SRC-PREFIX-1
        dest_prefix_set_name: CUSTOM-DEST-PREFIX-1
      - name: CUSTOM-APPLICATION-2
        protocols: [tcp]
        tcp_src_port_set_name: TCP-SRC-2
        tcp_dest_port_set_name: TCP-DEST-2
      - name: CUSTOM-voice-APPLICATION
        protocols: [udp]
        udp_src_port_set_name: UDP-SRC-VOICE
        udp_dest_port_set_name: UDP-DEST-VOICE
  field_sets:
    ipv4_prefixes:
      # This should not be rendered in any device
      - name: NOT-IN-ANY-APPLICATION
      - name: CUSTOM-SRC-PREFIX-1
        prefix_values:
          - 42.42.42.0/24
      - name: CUSTOM-DEST-PREFIX-1
        prefix_values:
          - 6.6.6.0/24
    l4_ports:
      # This should not be rendered in any device
      - name: NOT-IN-ANY-APPLICATION
      - name: TCP-SRC-2
        port_values:
          - 42
      - name: TCP-DEST-2
        port_values:
          - 666
          - 777
      - name: UDP-SRC-VOICE
        port_values:
          - 42000-42999
      - name: UDP-DEST-VOICE
        port_values:
          - 30000-30100
          - 31000-31100
